import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import {Store,encrypt,decrypt} from './store.mjs';
import {reviewSubmission} from './review.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const demo=process.env.INSTRUCTOR_DEMO==='1',port=Number(process.env.PORT||5180),origin=process.env.INSTRUCTOR_URL||`http://127.0.0.1:${port}`,secret=process.env.INSTRUCTOR_SECRET|| (demo?'local-demo-only':null),owner=process.env.INSTRUCTOR_GITHUB_LOGIN;
if(!demo&&(!secret||!owner||!process.env.GITHUB_APP_CLIENT_ID||!process.env.GITHUB_APP_CLIENT_SECRET||!process.env.GITHUB_WEBHOOK_SECRET||!origin.startsWith('https://')))throw Error('Configure INSTRUCTOR_URL, INSTRUCTOR_SECRET, INSTRUCTOR_GITHUB_LOGIN, GITHUB_APP_CLIENT_ID, GITHUB_APP_CLIENT_SECRET, and GITHUB_WEBHOOK_SECRET. Or use INSTRUCTOR_DEMO=1 for a localhost-only sample.');
const dir=path.join(root,'.instructor/private/onboarding');fs.mkdirSync(dir,{recursive:true});const store=new Store(path.join(dir,'class.sqlite'));
const missions=fs.readdirSync(path.join(root,'lessons/onboarding')).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(fs.readFileSync(path.join(root,'lessons/onboarding',f),'utf8')));
const oauthStates=new Map();let syncing=false;
async function github(endpoint,token){const r=await fetch('https://api.github.com'+endpoint,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`GitHub returned ${r.status}; reconnect or retry.`);return r.json();}
async function reconcile(){if(demo||syncing)return;syncing=true;try{for(const row of store.db.prepare('SELECT * FROM students').all())try{const token=decrypt(row.token,secret);const head=await github(`/repos/${row.repo}/commits?per_page=1`,token),revision=head[0]?.sha;if(!revision)continue;if(revision===row.revision){store.db.prepare('UPDATE students SET lastSync=?,error=NULL WHERE repo=?').run(new Date().toISOString(),row.repo);continue;}
 const tree=await github(`/repos/${row.repo}/git/trees/${revision}?recursive=1`,token);if(tree.truncated)throw Error('Repository tree too large to verify.');const expected=JSON.parse(fs.readFileSync(path.join(root,'.course/onboarding-baseline.json'),'utf8')).gitBlobs;const actual=Object.fromEntries(tree.tree.filter(n=>n.type==='blob').map(n=>[n.path,n.sha]));const changed=Object.keys(expected).filter(p=>actual[p]!==expected[p]);
 const data={release:{status:changed.length?'source mismatch':'matches instructor release build',note:'Student code is never built or executed on this server.'}};if(changed.length)data.protection={status:'protected files changed',paths:changed};for(const m of missions){try{const f=await github(`/repos/${row.repo}/contents/student-work/onboarding/${m.id}.json?ref=${revision}`,token);if(f.size>200000)throw Error('Submission too large');const work=JSON.parse(Buffer.from(f.content,'base64').toString());data[m.id]=reviewSubmission(m,work);if(changed.length)data[m.id].status="protected files changed; review blocked";}catch(e){if(!e.message.includes('404'))data[m.id]={status:'review error',error:e.message};}}
 store.db.prepare('UPDATE students SET revision=?,data=?,lastSync=?,error=NULL WHERE repo=?').run(revision,JSON.stringify(data),new Date().toISOString(),row.repo);
 }catch(e){store.db.prepare('UPDATE students SET error=? WHERE repo=?').run(e.message,row.repo);}}finally{syncing=false;}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function page(content){return `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Aircraft classroom</title><style>body{font:16px system-ui;max-width:1100px;margin:30px auto;padding:20px;color:#173b40;background:#f4f7f3}button,input,select,textarea{font:inherit;padding:10px;margin:5px}textarea{width:90%}pre{white-space:pre-wrap}article{background:white;padding:18px;margin:14px 0;border-radius:10px}small{color:#53696b}a{color:#17684f}</style>${content}`;}
const demoData=[{repo:'sample-team-a/course',login:'sample-team-a',revision:'sample only',lastSync:new Date().toISOString(),data:{mission02:{status:'revise',attempts:3,checks:[{message:'At 40 m/s the declared drag relationship gives 384 N.',actual:9.6,expected:384}],answer:{equation:'0.5*rho*V*S*Cd'},reflection:{observation:'The drag did not increase enough.'}}}},{repo:'sample-team-b/course',login:'sample-team-b',revision:'sample only',data:{mission01:{status:'checks passed; review reasoning',attempts:1,checks:[]}}}];
const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');const url=new URL(req.url,origin);const send=(code,data,type='application/json')=>{res.writeHead(code,{'Content-Type':type+'; charset=utf-8'});res.end(type==='application/json'?JSON.stringify(data):data);};const redirect=to=>{res.writeHead(302,{Location:to});res.end();};try{
 if(url.pathname==='/health')return send(200,{ready:true});
 if(url.pathname==='/login'){if(demo)return redirect('/');const state=randomBytes(24).toString('hex');oauthStates.set(state,Date.now());res.setHeader('Set-Cookie',`login_state=${state}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=600`);return redirect(`https://github.com/login/oauth/authorize?client_id=${encodeURIComponent(process.env.GITHUB_APP_CLIENT_ID)}&state=${state}&redirect_uri=${encodeURIComponent(origin+'/callback')}`);}
 if(url.pathname==='/callback'){const state=url.searchParams.get('state'),cookie=(req.headers.cookie||'').match(/(?:^|; )login_state=([^;]+)/)?.[1];if(!state||cookie!==state||Date.now()-(oauthStates.get(state)||0)>600000)throw Error('Login expired. Try again.');oauthStates.delete(state);const r=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify({client_id:process.env.GITHUB_APP_CLIENT_ID,client_secret:process.env.GITHUB_APP_CLIENT_SECRET,code:url.searchParams.get('code'),redirect_uri:origin+'/callback'})});const auth=await r.json();if(!auth.access_token)throw Error('GitHub login failed.');const user=await github('/user',auth.access_token);const token=store.createSession(user.login,encrypt(auth.access_token,secret));res.setHeader('Set-Cookie',`class_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=86400`);return redirect('/');}
 let body='';if(req.method==='POST'){for await(const chunk of req){body+=chunk;if(Buffer.byteLength(body)>250000)throw Error('Request too large.');}}
 if(url.pathname==='/webhook'&&req.method==='POST'){const wanted='sha256='+createHmac('sha256',process.env.GITHUB_WEBHOOK_SECRET||'').update(body).digest('hex'),actual=req.headers['x-hub-signature-256']||'';if(wanted.length!==actual.length||!timingSafeEqual(Buffer.from(wanted),Buffer.from(actual)))return send(403,{error:'Invalid webhook signature'});const id=req.headers['x-github-delivery'];if(!id)return send(400,{error:'Missing delivery ID'});const inserted=store.db.prepare('INSERT OR IGNORE INTO deliveries VALUES(?)').run(id);send(202,{queued:Boolean(inserted.changes)});if(inserted.changes)reconcile();return;}
 const cookie=(req.headers.cookie||'').match(/(?:^|; )class_session=([^;]+)/)?.[1],bearer=req.headers.authorization?.replace(/^Bearer /,''),session=demo?{login:'demo-instructor'}:(bearer?store.connection(bearer):store.session(cookie||''));const admin=demo||(!bearer&&session?.login===owner);
 if(bearer&&url.pathname!=='/api/feedback')return send(403,{error:'Connection codes can only read feedback.'});
 if(!session)return send(401,page('<h1>Aircraft classroom</h1><p>Sign in to connect your fork or open the instructor dashboard.</p><a href="/login">Sign in with GitHub</a>'),'text/html');
 if(req.method==='POST'&&url.pathname!=='/webhook'&&(!req.headers.origin||new URL(req.headers.origin).origin!==origin))return send(403,{error:'Use the classroom page to make changes.'});
 if(url.pathname==='/api/feedback'){const repo=url.searchParams.get('repo');if(!store.db.prepare('SELECT repo FROM students WHERE repo=? AND login=?').get(repo,session.login)&&!admin)return send(403,{error:'Repository is not enrolled for this account.'});return send(200,{messages:store.messages(repo),online:true});}
 if(url.pathname==='/api/dashboard'&&admin)return send(200,{students:demo?demoData:store.students(),syncing});
 if(url.pathname==='/api/export'&&admin)return send(200,{students:store.students(),feedback:store.db.prepare('SELECT * FROM feedback').all()});
 if(url.pathname==='/reply'&&req.method==='POST'&&admin){const form=new URLSearchParams(body),repo=form.get('repo'),mission=form.get('mission'),kind=form.get('kind')||'hint',message=form.get('body');if(!message?.trim()||message.length>4000)throw Error('Write a reply of 1–4,000 characters.');if(repo!=='*'&&!store.db.prepare('SELECT repo FROM students WHERE repo=?').get(repo)&&!demo)throw Error('Unknown student.');if(!['hint','override'].includes(kind))throw Error('Unknown feedback kind.');if(kind==='override'&&repo==='*')throw Error('Overrides must target one student.');const student=store.students().find(s=>s.repo===repo),snapshot=JSON.stringify(student?.data?.[mission]?.answer||{});store.db.prepare('INSERT INTO feedback(repo,mission,body,kind,snapshot,created) VALUES(?,?,?,?,?,?)').run(repo,mission,message,kind,snapshot,new Date().toISOString());return redirect('/');}
 if(url.pathname==='/enroll'&&req.method==='POST'&&!demo){const repo=new URLSearchParams(body).get('repo');if(!/^[\w.-]+\/[\w.-]+$/.test(repo))throw Error('Enter owner/repository.');const info=await github('/repos/'+repo,decrypt(session.access,secret));if(info.owner.login!==session.login||!info.fork||info.source?.full_name!=='vtaerodoctor-hokie/intro-aero-student-workflow-test')throw Error('Select your own fork of the classroom test repository.');if(store.students().length>=40&&!store.students().some(s=>s.repo===repo))throw Error('The 40-team pilot roster is full.');store.db.prepare('INSERT INTO students(repo,login,token) VALUES(?,?,?) ON CONFLICT(repo) DO UPDATE SET token=excluded.token').run(repo,session.login,session.access);reconcile();return redirect('/');}
 if(url.pathname==='/sync'&&req.method==='POST'&&admin){reconcile();return redirect('/');}
 if(url.pathname!=='/')return send(404,{error:'Not found'});
 if(!admin){const students=store.students().filter(s=>s.login===session.login);return send(200,page(`<h1>Your classroom connection</h1><p>Signed in as ${esc(session.login)}. Connect your fork once. Reviews run while your instructor’s service is open.</p><form method="POST" action="/enroll"><label>Your fork: <input name="repo" placeholder="your-account/repository" required></label><button>Enroll my fork</button></form><p>Paste this classroom address into the student app: <code>${esc(origin)}</code>. Use this session connection code (expires in 24 hours) only in your own Codespace:</p><pre>${esc(store.createConnection(session.login))}</pre>${students.map(s=>`<article><h2>${esc(s.repo)}</h2>${store.messages(s.repo).map(m=>`<p><b>${esc(m.mission)} · ${esc(m.kind)}</b> ${esc(m.body)}</p>`).join('')}</article>`).join('')}`),'text/html');}
 const rows=demo?demoData:store.students();send(200,page(`<h1>Aircraft instructor dashboard</h1><p>${demo?'LOCAL SAMPLE MODE • No live students or GitHub access':'Live class session • '+rows.length+' enrolled • refreshes every 30 seconds'}</p><form action="/sync" method="POST"><button>Check for new submissions</button></form><a href="/api/export">Export review backup</a><form action="/reply" method="POST"><input type="hidden" name="repo" value="*"><input type="hidden" name="mission" value="class"><textarea name="body" placeholder="Class announcement"></textarea><button>Send announcement</button></form>${rows.map(s=>`<article><h2>${esc(s.login)}</h2><a href="https://github.com/${esc(s.repo)}">${esc(s.repo)}</a><p>Last sync: ${esc(s.lastSync||'waiting')} · ${esc(s.revision||'no commit reviewed')}</p>${s.error?`<p>Connection error: ${esc(s.error)}</p>`:''}${Object.entries(s.data).map(([id,r])=>`<details><summary>${esc(id)} · ${esc(r.status)} · ${r.attempts||0} attempts</summary><pre>${esc(JSON.stringify(r,null,2))}</pre><form action="/reply" method="POST"><input type="hidden" name="repo" value="${esc(s.repo)}"><input type="hidden" name="mission" value="${esc(id)}"><select name="kind"><option value="hint">Targeted hint</option><option value="override">Allow progression for this answer</option></select><textarea name="body" placeholder="Explain the next check or the reason for an override" required></textarea><button>Send to student app</button></form></details>`).join('')}</article>`).join('')}<script>setTimeout(()=>{if(!document.querySelector('textarea:focus'))location.reload()},30000)</script>`),'text/html');
 }catch(e){send(400,{error:e.message});}});
server.listen(port,demo?'127.0.0.1':'0.0.0.0',()=>console.log(`Instructor dashboard: ${origin}${demo?' (localhost-only sample mode)':''}`));if(!demo){reconcile();setInterval(reconcile,60000).unref();}
