import {useEffect,useRef,useState} from 'react';
import {sectionNames,runMission,progress,markdown,implementationPrompt} from './engine.js';
import {runStudentCode} from './codeRunner.js';
import {studentRequest} from '../missions/AnswerEditor.jsx';
import EngineeringPlot from '../visualization/EngineeringPlot.jsx';
import {download} from '../flight/storage.js';
import './game.css';
import Experiment from './Experiment.jsx';
const packages=import.meta.glob('../../../lessons/onboarding/*.json',{eager:true,import:'default'});
const missions=Object.values(packages).sort((a,b)=>a.number-b.number);
export default function Game(){
 const [selected,setSelected]=useState(0),[work,setWork]=useState({}),[notice,setNotice]=useState('Connecting to your Codespace…'),[repo,setRepo]=useState(null),[online,setOnline]=useState(false),[busy,setBusy]=useState(false),[showAll,setShowAll]=useState(false),[hints,setHints]=useState({});
 const [guard,setGuard]=useState({passed:false,errors:[]});
 const [classroom,setClassroom]=useState({messages:[]}),[classUrl,setClassUrl]=useState(''),[classCode,setClassCode]=useState(''),[classNotice,setClassNotice]=useState('Connect when your instructor opens a class session.');
 useEffect(()=>{let live=true;const refresh=()=>studentRequest('classroom').then(d=>{if(live){setClassroom(d);if(d.connected)setClassNotice('Instructor connection active. Feedback refreshes every 30 seconds.');}}).catch(()=>{if(live)setClassNotice('Instructor session unavailable. Your drafts and experiments still work.');});refresh();const timer=setInterval(refresh,30000);return()=>{live=false;clearInterval(timer);};},[]);
 async function connectClass(){try{const d=await studentRequest('classroom-connect',{url:classUrl,token:classCode});setClassroom(d);setClassCode('');setClassNotice('Connected to your instructor.');}catch(e){setClassNotice(e.message);}}
 const hashes=useRef({}),latest=useRef({}),saving=useRef(false),versions=useRef({}),timers=useRef({});
 const mission=missions[selected],record=work[mission?.id]||{answer:{},reflection:{}},states=progress(missions,work,classroom.messages),state=states[selected];
 useEffect(()=>{let active=true;studentRequest('state').then(data=>{if(!active)return;const next={};for(const m of missions){const p=`student-work/onboarding/${m.id}.json`,file=data.files[p];hashes.current[m.id]=file.hash;try{next[m.id]=JSON.parse(file.text);}catch{}let draft;try{draft=JSON.parse(localStorage.getItem('onboarding:'+location.host+':'+m.id));}catch{}if(draft?.base===file.hash)next[m.id]=draft.work;}
 latest.current=next;setWork(next);setRepo(data.repository);setGuard(data.onboardingProtection);setOnline(true);setNotice('Connected. Drafts save in your Codespace; submit attempts to checkpoint them on GitHub.');}).catch(e=>setNotice(e.message));return()=>{active=false;Object.values(timers.current).forEach(clearTimeout);};},[]);
 async function save(id){if(!online)return false;if(saving.current){timers.current[id]=setTimeout(()=>save(id),500);return false;}saving.current=true;const revision=versions.current[id],snapshot=latest.current[id];try{const r=await studentRequest('save',{name:`student-work/onboarding/${id}.json`,text:JSON.stringify(snapshot,null,2)+'\n',expectedHash:hashes.current[id]});hashes.current[id]=r.hash;if(versions.current[id]===revision)localStorage.removeItem('onboarding:'+location.host+':'+id);else{localStorage.setItem('onboarding:'+location.host+':'+id,JSON.stringify({base:r.hash,work:latest.current[id]}));timers.current[id]=setTimeout(()=>save(id),300);}setNotice('Draft saved in your Codespace.');return true;}catch(e){setNotice('Draft retained on this device. '+e.message);return false;}finally{saving.current=false;}}
 function update(value){const id=mission.id;latest.current={...latest.current,[id]:value};versions.current[id]=(versions.current[id]||0)+1;setWork(latest.current);try{localStorage.setItem('onboarding:'+location.host+':'+id,JSON.stringify({base:hashes.current[id],work:value}));}catch{setNotice('Device storage unavailable; save your workspace before closing.');}clearTimeout(timers.current[id]);timers.current[id]=setTimeout(()=>save(id),1000);}
 async function run(){setBusy(true);try{const fresh=await studentRequest('state');setGuard(fresh.onboardingProtection);if(!fresh.onboardingProtection.passed){setNotice('Restore protected files before running. Your answers are preserved.');setBusy(false);return;}}catch(e){setNotice(e.message);setBusy(false);return;}const snapshot=JSON.stringify(record.answer),result=runMission(mission,record.answer);if(result.runnable&&mission.codeCases){const checks=await runStudentCode(record.answer.code,mission.codeCases);result.checks.push(...checks);result.passed=result.checks.every(c=>c.passed);result.codeEvidence='Student-browser execution; not independently verified by the instructor server.';}
 const attempt={id:crypto.randomUUID(),missionVersion:mission.version,answerSnapshot:snapshot,at:new Date().toISOString(),result};update({...record,attempt,reflection:{},attempts:[...(record.attempts||[]),attempt].slice(-100)});setBusy(false);}
 async function submit(){setBusy(true);clearTimeout(timers.current[mission.id]);if(await save(mission.id)){try{const r=await studentRequest('onboarding-submit',{id:mission.id,expectedHash:hashes.current[mission.id]});setNotice(`Saved to GitHub: ${r.revision.slice(0,8)}. Your instructor can review this attempt.`);}catch(e){setNotice('GitHub submission failed; your local work is retained. '+e.message);}}setBusy(false);}
 if(!mission)return <p>No onboarding packets installed.</p>;
 const result=record.attempt?.result;
 return <main className="game"><header><p>CHAPTER 6 / CONTROL AUTHORITY</p><h1>One missing piece.<br/>One experiment to investigate.</h1><p>Twelve missions in class. One independent homework challenge.</p><strong>{states.filter(s=>s.complete).length} / 13 completed</strong><p role="status">{notice}</p>{repo&&<small>Working in {repo.owner}/{repo.repo} · {repo.branch}</small>}</header>
 <details className="classroom"><summary>Instructor feedback &amp; classroom connection</summary><p>{classNotice}</p><label>Instructor classroom address<input value={classUrl} onChange={e=>setClassUrl(e.target.value)} placeholder="https://…-5180.app.github.dev"/></label><label>Connection code<input type="password" value={classCode} onChange={e=>setClassCode(e.target.value)} autoComplete="off"/></label><button onClick={connectClass}>Connect my fork</button>{classroom.messages.map(m=><p key={m.id}><strong>{m.mission} · {m.kind}</strong> {m.body}</p>)}</details>
 <nav aria-label="Mission map">{missions.map((m,i)=><button key={m.id} aria-current={i===selected?'step':undefined} onClick={()=>{setSelected(i);setShowAll(false);}}><b>{m.number===13?'HW':m.number}</b><span>{m.title}</span><small>{states[i].state}</small></button>)}</nav>
 <article>{!guard.passed&&guard.errors.map(e=><p className="callout" key={e}>{e}</p>)}{classroom.messages.filter(m=>m.mission===mission.id||m.mission==='class').map(m=><aside className="callout" key={m.id}><strong>Instructor: </strong>{m.body}{m.kind==='override'&&<small> Applies only to the reviewed answer.</small>}</aside>)}{record.attempt?.missionVersion&&record.attempt.missionVersion!==mission.version&&<p className="callout">This mission now teaches Chapter 6 control authority. Your earlier attempt is preserved, but its result cannot complete the revised exercise. Read the new packet and revise your answers.</p>}<p className="eyebrow">{mission.number===13?'HOMEWORK • ALL TWELVE SECTIONS':'YOUR TASK • '+sectionNames[mission.missing[0]]}</p><h2>{mission.title}</h2><p><strong>{mission.chapter}</strong></p><p>{mission.brief}</p><p>{mission.number===13?'Build the complete engineering specification.':'11 sections supplied · 1 section yours. Read the worked material whenever it helps.'}</p>
 {state.state==='locked'&&<p className="callout">Preview this mission now. Complete the previous mission’s experiment and reflection to run it.</p>}
 <button onClick={()=>setShowAll(!showAll)}>{showAll?'Collapse supplied sections':'Show all supplied sections'}</button>
 <div className="specification">{sectionNames.map((title,i)=>mission.missing.includes(i)?<section key={title} className="your-section"><h3>{i+1}. {title} <small>YOUR WORK</small></h3>{mission.fields.filter(f=>f.section===i).map(f=><label key={f.id}>{f.label}{f.type==='select'?<select value={record.answer[f.id]??''} onChange={e=>update({...record,answer:{...record.answer,[f.id]:e.target.value}})} disabled={!online||busy}><option value="">Choose…</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='number'?<input type="number" step="any" value={record.answer[f.id]??''} onChange={e=>update({...record,answer:{...record.answer,[f.id]:e.target.value}})} disabled={!online||busy}/>:<textarea rows={f.type==='code'?12:3} value={record.answer[f.id]??''} onChange={e=>update({...record,answer:{...record.answer,[f.id]:e.target.value}})} disabled={!online||busy} spellCheck={f.type!=='code'}/>}</label>)}</section>:<details key={title} open={showAll||undefined}><summary>{i+1}. {title} · PROVIDED</summary><pre>{mission.supplied[i]}</pre></details>)}</div>
 <div className="actions"><button disabled={!online||busy||state.state==='locked'} onClick={run}>{busy?'Working…':'Try my answer — run experiment'}</button><button onClick={()=>setHints({...hints,[mission.id]:Math.min(3,(hints[mission.id]||0)+1)})}>Give me a hint</button>{mission.codeCases&&<button onClick={()=>download(mission.id+'-implementation-prompt.txt',implementationPrompt(mission,record),'text/plain')}>Export implementation prompt</button>}<button onClick={()=>download(mission.id+'-spec.md',markdown(mission,record),'text/markdown')}>Export specification</button></div>
 {(hints[mission.id]||0)>0&&<aside className="callout">{mission.hints.slice(0,hints[mission.id]).map(h=><p key={h}>{h}</p>)}</aside>}
 {result&&<section className="experiment"><h3>{!result.runnable?'Make the answer runnable':result.passed?'Experiment checks passed':'Useful failure — inspect and revise'}</h3>{state.stale&&<p className="callout">Your answer or mission version changed. Run again to create current evidence.</p>}<ul>{result.checks.map((c,i)=><li key={i} className={c.passed?'pass':'fail'}><strong>{c.passed?'✓':'↻'} {c.message}</strong>{c.actual!==undefined&&<p>Your result: {String(c.actual)} {c.expected!==undefined&&`· Reference: ${String(c.expected)}`}</p>}{c.error&&<p>{c.error}</p>}</li>)}</ul>{result.traces?.length>0&&<EngineeringPlot plot={{title:'Experiment comparison',xLabel:mission.sweep.variable,yLabel:mission.sweep.units||'Declared model output',series:[{label:'Configured experiment',points:result.traces.filter(r=>Number.isFinite(r.supplied)).map(r=>({x:r.x,y:r.supplied}))},{label:'Supplied reference / requirement',points:result.traces.filter(r=>Number.isFinite(r.reference)).map(r=>({x:r.x,y:r.reference}))}]}}/>}<Experiment mission={mission} result={result}/>{mission.challenges&&<section><h4>Control-authority challenge results</h4><p>Each row changes only its named input. Positive or zero margin meets the static requirement.</p><table><thead><tr><th>Condition</th><th>Available (N m)</th><th>Required (N m)</th><th>Margin (N m)</th><th>Screen</th></tr></thead><tbody>{mission.challenges.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.available.toFixed(2)}</td><td>{c.required.toFixed(2)}</td><td>{c.margin.toFixed(2)}</td><td>{c.margin>=0?'Pass':'Insufficient authority'}</td></tr>)}</tbody></table></section>}<p>{result.codeEvidence||'Reproducible model checks. Written reasoning still needs instructor review.'}</p><p>Attempts retained: {record.attempts?.length||0}. An unsuccessful attempt can also be submitted.</p></section>}
 {result?.runnable&&<section className="reflection"><h3>Explain the evidence</h3>{[['observation','What did you observe?'],['change','What did you change or confirm, and why?'],['limit','What does this experiment not establish?']].map(([k,l])=><label key={k}>{l}<textarea value={record.reflection?.[k]||''} onChange={e=>update({...record,reflection:{...record.reflection,[k]:e.target.value}})}/></label>)}<label>Do the current checks support your bounded answer?<select value={record.reflection?.result||''} onChange={e=>update({...record,reflection:{...record.reflection,result:e.target.value}})}><option value="">Choose…</option><option value="supported">Yes, within the stated limits</option><option value="revise">No, I need to revise it</option></select></label><p>Completion checks that a reflection is present; it does not grade the quality of your reasoning.</p></section>}
 <div className="actions"><button disabled={!online||busy||!record.attempt} onClick={submit}>Submit attempt to GitHub</button>{state.complete&&selected<12&&<button onClick={()=>setSelected(selected+1)}>Mission complete — next challenge →</button>}</div>
 </article></main>;
}
