import { useEffect,useRef,useState } from 'react';
import { mission } from './manifest.js';
import { answerFields,replaceAnswer } from './answerFields.js';
import { validateDocument } from './validation.js';
export async function studentRequest(action,body){const response=await fetch(`/api/student/${action}`,body?{method:'POST',headers:{'Content-Type':'application/json','X-Student-Workspace':'1'},body:JSON.stringify(body)}:{cache:'no-store'});let data;try{data=await response.json();}catch{throw Error('Saving requires the running Codespace lab. This static preview cannot save to GitHub.');}if(!response.ok)throw Error(data.error||'Save failed.');return data;}
const blanks=import.meta.glob('../../../templates/missions/week06/*.md',{eager:true,query:'?raw',import:'default'});
export default function AnswerEditor({stage,onRefresh,onNext}){
 const name=`${mission.directory}/${stage.file}`;
 const [text,setText]=useState(''),[state,setState]=useState(null),[message,setMessage]=useState('Connecting to your workspace…'),[errors,setErrors]=useState([]),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[link,setLink]=useState(null);
 const hash=useRef(null),latest=useRef(''),version=useRef(0);
 const key=`mission-draft:${location.host}:${name}`;
 useEffect(()=>{let active=true;setReady(false);setDirty(false);setLink(null);studentRequest('state').then(data=>{if(!active)return;setState(data);hash.current=data.files[name].hash;const saved=data.files[name].text;let draft;try{draft=JSON.parse(localStorage.getItem(key));}catch{}const template=Object.entries(blanks).find(([p])=>p.endsWith('/'+stage.file))?.[1]||'';const initial=draft?.base===hash.current?draft.text:saved||template.replace(/<!-- STUDENT COMPLETE -->/g,'');setText(initial);latest.current=initial;setReady(true);setDirty(Boolean(draft?.base===hash.current&&initial!==saved));setMessage(draft&&draft.base!==hash.current?'An older device draft is available below; the repository version is shown.':'Connected to your repository.');}).catch(e=>active&&setMessage(e.message));return()=>{active=false;};},[name]);
 function update(value){latest.current=value;version.current++;setText(value);setDirty(true);try{localStorage.setItem(key,JSON.stringify({text:value,base:hash.current}));setMessage('Draft saved on this device.');}catch{setMessage('Device storage unavailable. Keep this window open until workspace saving succeeds.');}}
 async function save(){const value=latest.current,revision=version.current;setSaving(true);try{const result=await studentRequest('save',{name,text:value,expectedHash:hash.current});hash.current=result.hash;if(revision===version.current){setDirty(false);localStorage.removeItem(key);}else localStorage.setItem(key,JSON.stringify({text:latest.current,base:hash.current}));setMessage('Draft saved in your Codespace. GitHub checkpoint pending.');await onRefresh();return true;}catch(e){setMessage(e.message);return false;}finally{setSaving(false);}}
 useEffect(()=>{if(!ready||!dirty||saving)return;const timer=setTimeout(()=>{save();},1200);return()=>clearTimeout(timer);},[text,ready,dirty]);
 async function check(){if(!await save())return;const problems=validateDocument(stage,latest.current);setErrors(problems);if(problems.length){setMessage('Complete the items below before creating a checkpoint.');return;}setSaving(true);try{const result=await studentRequest('checkpoint',{name});setLink(result.url);setMessage('Saved to GitHub. Structural checks passed; engineering reasoning still needs review.');await onRefresh();onNext?.();}catch(e){setMessage(`Draft retained. GitHub save failed: ${e.message}`);}finally{setSaving(false);}}
 const parts=answerFields(text);
 function sectionChange(heading,value){update(replaceAnswer(text,heading,value));}
 return <section className="answer-editor"><h3>Your answers</h3><p>Write here. Drafts save automatically in your Codespace. “Save checkpoint to GitHub” records this stage in your fork.</p>{state&&<p>Repository: <a href={state.repository.url} target="_blank" rel="noreferrer">{state.repository.owner}/{state.repository.repo}</a> · {state.repository.branch}</p>}{ready&&stage.headings.map(heading=><label key={heading}>{heading}<textarea value={parts[heading]||''} onChange={e=>sectionChange(heading,e.target.value)} rows={5}/></label>)}<p role="status">{message}</p>{errors.length>0&&<ul role="alert">{errors.map(e=><li key={e}>{e}</li>)}</ul>}<button disabled={!ready||saving} onClick={check}>{saving?'Saving…':'Save checkpoint to GitHub'}</button>{link&&<a href={link} target="_blank" rel="noreferrer">View checkpoint</a>}<details><summary>Recover a device draft or inspect Markdown</summary><button onClick={()=>{try{const draft=JSON.parse(localStorage.getItem(key));if(draft?.text)update(draft.text);}catch{}}}>Restore device draft</button><textarea aria-label="Stage Markdown" value={text} onChange={e=>update(e.target.value)} disabled={!ready} rows={14}/></details></section>;
}
