import { useEffect,useState } from 'react';
import { mission } from './manifest.js';
import { studentRequest } from './AnswerEditor.jsx';
export default function ImplementationEditor(){
 const [name,setName]=useState(mission.implementationPaths[0]),[text,setText]=useState(''),[hash,setHash]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[results,setResults]=useState(null),[dirty,setDirty]=useState(false);
 useEffect(()=>{let active=true;setHash(null);studentRequest('state').then(s=>{if(active){setText(s.files[name].text);setHash(s.files[name].hash);}}).catch(e=>setNotice(e.message));return()=>{active=false;};},[name]);
 async function verify(){setBusy(true);setNotice('Running tests and production build…');try{const result=await studentRequest('verify',{});setResults(result.results);setNotice(result.notice);}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 async function save(){setBusy(true);try{const saved=await studentRequest('save',{name,text,expectedHash:hash});setHash(saved.hash);setDirty(false);await studentRequest('checkpoint',{name});setNotice('Implementation file saved to GitHub.');}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 return <section className="answer-editor"><h3>Implementation files</h3><p>Paste the code from your approved implementation into its matching file. Save each file before switching. Code generation is not built into this prototype.</p><select aria-label="Implementation file" disabled={dirty||busy} value={name} onChange={e=>setName(e.target.value)}>{mission.implementationPaths.map(p=><option key={p}>{p}</option>)}</select><textarea aria-label="Implementation code" rows={20} value={text} onChange={e=>{setText(e.target.value);setDirty(true);setNotice("Unsaved code. Save this file before switching.");}}/><button disabled={!hash||busy} onClick={save}>Save implementation checkpoint</button><button disabled={busy||!hash} onClick={verify}>Run tests and build</button><p role="status">{notice}</p>{results?.map(r=><details key={r.command}><summary>{r.command}: {r.passed?'passed':'failed'}</summary><pre>{r.output}</pre></details>)}<p>Independent instructor verification is not included in this public test shell. Passing your own tests will not unlock a claim of independent verification.</p></section>;
}
