import ImplementationEditor from './ImplementationEditor.jsx';
import AnswerEditor from './AnswerEditor.jsx';
import { mission } from './manifest.js';
import { download } from '../flight/storage.js';
const templates=import.meta.glob('../../../templates/missions/week06/*.md',{eager:true,query:'?raw',import:'default'});
const tasks={
 question:{title:'Write one question your model can answer',why:'Before calculating anything, decide what response you need and what evidence would count as failure.',work:['Name the event you are investigating.','State the aircraft condition supplied in the mission dossier.','State the requested response, including its units.','Write one question that connects the control input to that response.','Define what result would make the answer “no”.'],frame:'At [aircraft condition], can [control effector] provide enough [physical quantity] to achieve [requested response]?',check:'All five sections need your own response. This checks completeness; it does not decide whether your engineering question is good.',next:'Next you will choose the physics relationships needed to answer your question.'},
 model:{title:'Choose the relationships that connect demand to capability',why:'A useful model connects the requested motion, the required moment and the available control contribution.',work:['List the relationships you need from the lesson.','Explain what each relationship contributes to the answer.','Declare positive directions and signs.','Describe how the relationships connect; do not write software yet.'],check:'Relationships, sign convention and model chain must be explained.',next:'Next you will map the aircraft dossier to the variables in your model.'},
 inputs:{title:'Map the supplied aircraft data to your model',why:'Correct equations still give misleading answers when the inputs, units or configuration do not match.',work:['Identify each input your chosen relationships require.','Enter the supplied values in the worksheet’s named fields, preserving the requested units.','Explain which quantities are supplied and where they came from.','Flag missing evidence instead of inventing a value.'],check:'Named numerical fields and their units are checked. The reference check also checks the selected case.',next:'Next you will choose the outputs that actually answer the question.'},
 outputs:{title:'Decide what results you need to see',why:'The output should support an engineering decision, not just display numbers.',work:['List the quantities needed to compare the requested response with available control.','Give the unit of each output.','Explain why each output is needed.','Distinguish control capacity from the amount actually commanded.'],check:'Required outputs, units and purpose must be present.',next:'Next you will explain the assumptions behind these results.'},
 assumptions:{title:'State what you are simplifying',why:'A model is useful only when its simplifying assumptions are understood.',work:['List the assumptions that make your chosen model manageable.','For each assumption, explain the physical effect you are leaving out.','Identify an assumption that could materially change your conclusion.'],check:'List assumptions and their consequences. A human still reviews whether they are justified.',next:'Next you will draw the boundary around what the model can claim.'},
 validity:{title:'Draw the boundary around your claim',why:'Passing a small calculation does not establish that an entire aircraft operation is safe.',work:['Write the limited claim your model can support.','List the broader claims it cannot support.','State the conditions and operating limits under which you will use it.'],check:'Supported claim, excluded claims and operating limits must be present.',next:'Next you will predict how the answer changes before looking at calculated behavior.'},
 predictions:{title:'Predict three changes before running the model',why:'Your predictions will help you recognize whether the eventual software behaves physically.',work:['Predict what happens when speed decreases while other terms are fixed.','Predict what happens when inertia increases at fixed net moment.','Predict what happens when the competing nose-down moment grows.','Explain the reason for each prediction, not just the direction of change.'],check:'All three predictions must be recorded. Their engineering quality still needs review.',next:'This unlocks control-surface movement only. Calculated aircraft response waits for implementation verification.'},
 reference:{title:'Calculate one trusted result by hand',why:'You need an independent expectation before AI generates the implementation.',work:['Use the declared reference condition from the dossier.','Show substitutions and intermediate steps, including signs.','Check dimensions and unit conversions.','Enter your final results in the machine-readable reference fields.'],check:'Your reference values and units are compared with the independent check. This works before implementation files exist.',next:'Next you will design tests that can catch different kinds of mistakes.'},
 verification:{title:'Specify tests before asking AI to code',why:'Different test types catch different errors. The generated software must be accountable to expectations you established first.',work:['Give a numerical case with independently calculated expected values.','Give a behavioral case that checks a physical trend or scaling.','Give a boundary or invalid-input case.','Explain what error each test would catch.'],check:'Numerical, behavioral and boundary cases must all be specified.',next:'Next you will describe how the verified model should appear in the application.'},
 requirements:{title:'Specify the feature without redesigning the app',why:'AI needs a bounded integration contract in addition to the equations.',work:['Describe the controls, indicators and outputs the feature must supply.','List the three permitted implementation files exactly.','State what the feature must not do or claim.','Review the compiled specification before sending it to AI.'],check:'Required sections and the exact three-file allowlist are checked.',next:'Next you will ask AI for an interpretation, review it, and then authorize implementation.'},
 implementation:{title:'Have AI implement your approved specification',why:'AI implements your engineering decisions; it does not supply independent evidence that those decisions are correct.',work:['Export the AI specification using the button below.','Send it to ChatGPT and request an Implementation Interpretation first.','Check the physics, signs, units, assumptions and tests against your work.','Only when satisfied, approve the interpretation.','Paste the returned code into the three implementation fields below and save each file.','Click Run tests and build below. Use specific failed checks to diagnose and revise the implementation.'],check:'Student tests, independent checks, the complete suite, the build and protected files must pass for this source revision.',next:'Passing unlocks the initial-response experiment. Then run the challenges and use the evidence for your decision.'},
 decision:{title:'Use the experiment evidence to defend a decision',why:'The goal is a bounded engineering conclusion, not merely a working animation.',work:['For each challenge, record a prediction before running it.','Run the model, inspect the results and save the evidence.','Compare the results with your predictions and initial question.','Choose retain, narrow, revise or withdraw, and explain the supported claim and condition.','Identify the largest uncertainty and the evidence you need next.','Export the challenge records into the mission evidence folder for repository validation.'],check:'All six current challenge records and the decision sections are required. Completion is not a grade for your reasoning.',next:'Assess the crosswind requirement: recognize when a different engineering model is needed.'},
};
export default function StageGuide({stage,files,reference,errors,onNext,onExport,onRefresh}){
 const task=tasks[stage.id],path=`${mission.directory}/${stage.file}`;
 const template=Object.entries(templates).find(([path])=>path.endsWith('/'+stage.file))?.[1];
 const [previous,next]=[mission.stages[stage.number-2],mission.stages[stage.number]];
 return <section className="mission-card student-task">
  <p className="mission-kicker">Student task {stage.number} of 12 · {reference?'instructions for the student workflow':stage.status}</p>
  <h2>{task.title}</h2><p>{task.why}</p>
  {stage.number===1&&<div className="student-sentence"><strong>Mission brief</strong><p>Investigate the trainer’s initial nose-up pitch response at 20 m/s. The requested angular acceleration is 0.12 rad/s². Your question should compare elevator capability with the moment needed to achieve that response.</p><p>Supplied condition: mass 900 kg; pitch inertia 5,000 kg·m²; density 1.20 kg/m³; area 27.25 m²; chord 4 m; other pitching moment −750 N·m; usable pitching-moment coefficient increment 0.153. Nose-up is positive.</p><p>Assess initial pitch authority only. This experiment does not establish successful takeoff or aircraft safety.</p></div>}
  <h3>What you do</h3><ol>{task.work.map(item=><li key={item}>{item}</li>)}</ol>
  {task.frame&&<div className="student-sentence"><strong>A starting sentence</strong><p>{task.frame}</p><small>Fill the brackets with your choices. This is a writing aid, not a completed answer.</small></div>}
  {!reference&&<AnswerEditor key={stage.id} stage={stage} onRefresh={onRefresh} />}
  {!reference&&stage.id==='implementation'&&<ImplementationEditor/>}
  <h3>How you know you are ready</h3><p>{task.check}</p>
  {!reference&&errors.length>0&&<details><summary>What still needs attention ({errors.length})</summary><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></details>}
  <p className="student-next"><strong>What happens next:</strong> {task.next}</p>
  <details><summary>{reference?'Read the completed instructor example':'Read your saved worksheet'}</summary><pre>{files[stage.file]||'No worksheet has been saved yet.'}</pre></details>
  <div className="mission-actions">{previous&&<button onClick={()=>onNext(previous.id)}>← Previous task</button>}{stage.number>=10&&<button onClick={onExport}>Export AI specification</button>}{next&&<button onClick={()=>onNext(next.id)}>{reference?'Read next student task':'Go to next task'} →</button>}</div>
 </section>;
}
